export const SET_HISTORY_TRANSACTION = 'SET_HISTORY_TRANSACTION';
export const CLEAR_HISTORY_TRANSACTION = 'CLEAR_HISTORY_TRANSACTION';
export const UPDATE_HISTORY_TRANSACTION = 'UPDATE_HISTORY_TRANSACTION';
