name: Node.Js CD

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy react.komoverse.dev
        uses: actions/checkout@v2
      - name: Download artifact
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /opt/bitnami/projects/game-hub-react
            git pull origin develop
            pm2 restart game-hub-react
